title: Shahid Raza Ansari
url: "https://www.shahidraza.me"
remote_theme: ankitsultana/researcher@gem
markdown: kramdown
google_analytics: "G-TZ67FKMBXR"

tracking_id: G-TZ67FKMBXR

footer: yes
footer_url: "https://github.com/mrpascal1"
footer_text: "Made with 💻 in India"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Blogs"
   link: "/blogs"
 - name: "Resume"
   link: "shahid_raza_resume.pdf"
 - name: "About"
   link: "/about"
 